apiVersion: v1
kind: Namespace
metadata:
  name: exposer-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exposer-controller-cr
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: exposer-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exposer-controller-cr
subjects:
  - kind: ServiceAccount
    name: exposer-controller-sa
    namespace: exposer-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exposer-controller
  name: exposer-controller
  namespace: exposer-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposer-controller
  strategy: {}
  template:
    metadata:
      labels:
        app: exposer-controller
    spec:
      containers:
        - image: poneding/exposer-controller:0.1.0
          imagePullPolicy: Always
          name: exposer-controller
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: exposer-controller-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exposer-controller-sa
  namespace: exposer-test
